name: Build Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write # Crucial for creating releases

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install pyinstaller requests # Added requests for the updater
          if (Test-Path "backend/requirements.txt") { pip install -r backend/requirements.txt }

      - name: Build Python Updater
        run: |
          cd updater
          python -m PyInstaller --noconsole --onefile --uac-admin updater.py

      - name: Build Python Backend
        run: |
          cd backend
          python -m PyInstaller --noconfirm --onedir --windowed app.py

      - name: Install Frontend Dependencies
        run: bun install

      - name: Build Vite Assets
        run: bun run build

      - name: Build and Publish Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This action runs 'electron-builder' automatically
          # It will pick up the files built in previous steps
          release: true
